services:
  ktor-v3_4_3:
    build:
      context: "./ktor-sample-3.4.3/"
      dockerfile: Dockerfile
    ports:
      - "${PORT_V3_4_3:-8043}:8080"
    volumes:
      - "./ktor-sample-3.4.3/:/app"

  ktor-v3_5_0:
    build:
      context: "./ktor-sample-3.5.0/"
      dockerfile: Dockerfile
    ports:
      - "${PORT_V3_5_0:-8050}:8080"
    volumes:
      - "./ktor-sample-3.5.0/:/app"
